### ISSUE TITLE
Incorrect instructions when generating token-factory contract

### ISSUE THREAD

**Issue by fsodano** [terra-money/docs#337]
This is what the instructions read at the moment:

![image](https://user-images.githubusercontent.com/844181/167243980-d143ab44-b6a2-417a-9e71-2d5f67697a8c.png)

The previous step instructs the user to go inside the `contracts` folder and then to cd into a `token-factory` folder. However, the only way to get this step to work is by running the command from the root directory, otherwise, the command complains about not being able to find a `contracts` folder.

`Error: ENOENT: no such file or directory, chdir '/home/user/project/contracts' -> './contracts'`

Perhaps it would be clearer if you stated that the command needs to be run from the project root?

**Comment by hanjukim** [comment]
@octalmage can you assist?

**Comment by octalmage** [comment]
Yes I’m on it! @emidev98 can you take a look?

**Comment by emidev98** [comment]
Hello @fsodano, seems right the guide was outdated since the  [new 0.3.0 release of Terrain](https://github.com/terra-money/terrain/releases) and Terra 2.0. But I updated the guide here https://github.com/terra-money/docs/pull/382. Please subscribe to that PR to see when the new version is released. Thanks!
