### ISSUE TITLE
Can I bring a memo for cw20 transfer?

### ISSUE THREAD

**Issue by coder-chenda** [terra-money/docs#381]

**Comment by emidev98** [comment]
Hello, 

Since the blockchain state changes are done thru transactions all transactions accept memo field. You can check this [interface from terra.js to see how to setup the memo](https://github.com/terra-money/terra.js/blob/870e74dffd65bef2c9e01a058cb4532244ba3413/src/client/lcd/api/TxAPI.ts#L122-L131). 
For more questions please go to [Terra Discord, here you have an invite](https://discord.com/invite/terra-money), this space should be used only for issues related to the docs.

Thanks,
Emi
