### ISSUE TITLE
Outdated/renamed commands

### ISSUE THREAD

**Issue by taitruong** [terra-money/docs#400]
Command examples did not work while working through this: https://docs.terra.money/docs/develop/guides/smart-contracts/interact-with-smart-contract.html

docs: contract-store => should be: contract-info
docs: terrad tx wasm instantiate => requires 2 more flags
docs: terrad query wasm code => does not show metadata, instead it downloads wasm bytecode

For more details, read my comments in discord: https://discord.com/channels/983359798059892766/983726224008413234/989833390574407680

**Comment by taitruong** [comment]
Also all examples with --fees flag the values are way too small. Had to add an extra 0, e.g --fees=1000000uluna instead of --fees=100000uluna
And in many cases I had an 'out of gas in location' error. So it'd be cool mentioning the --gas-adjustment flag in the docs.

**Comment by evanorti** [comment]
I believe the specific issues you were having were fixed in the docs a while ago.

Recently I have been working on documenting Terrad in its entirety. 

Complete docs for all commands and subcommands can be found here:
https://docs.terra.money/develop/terrad/commands/

The revamped Terrad usage guide can be found here:
https://docs.terra.money/develop/terrad/using-terrad

Thank you for bringing this up.

Cheers!
