### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by dev8723** [terra-money/docs#501]
Discord link in the [doc](https://docs.terra.money/develop/get-started/#terra-discord-server) is broken. Getting `invite invalid`

**Comment by evanorti** [comment]
Thank you for pointing this out!

I will update these. 

For now, you can use these links:

Main Discord: [terra.sc/discord](http://terra.sc/discord)
Validator Discord: [terra.sc/validatordiscord](http://terra.sc/validatordiscord)

**Comment by luuuu-learning** [comment]
Hi @evanorti Thanks for the response. For some reason I still cannot join via the link [terra.sc/discord](http://terra.sc/discord), I know this is also the link from terra.money homepage. Not sure if it's because of my own discord account or something (I did joined the old terra server (classic), but that disappeared in server list as well). Maybe there's some weird issue with discord.
